name: "Build and Push Docker Image (Native)"

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        target:
        - go-app
        - go-app-2
        include:
        - target: go-app
          workdir: ./go-app
        - target: go-app-2
          workdir: ./go-app-2

    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read # to fetch the repository content
      # id-token: write # for signing attestation(s) with GitHub OIDC Token
      packages: write # to push the built image to GitHub Container Registry
    with:
      output: image
      push: true
      platforms: linux/amd64,linux/arm64
      meta-images: ghcr.io/${{ github.repository }}/${{ matrix.target }}
      context: ${{ matrix.workdir }}
      set-meta-annotations: true
      sign: false
      meta-tags: |
        type=raw,value=sha-{{sha}}
        type=raw,value=latest,enable={{is_default_branch}}
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
  chart:
    runs-on: ubuntu-latest
    permissions:
      packages: write # to push the built image to GitHub Container Registry
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Modify values.yaml
        run: |
          yq -i '.image.tag="${{ github.sha }}"' charts/go-app/values.yaml


      - name: Chart | Push
        uses: appany/helm-oci-chart-releaser@v0.5.0
        with:
          name: go-app
          repository: ${{ github.repository }}/charts
          tag: 0.1.0
          path: charts/go-app # Default charts/{name}
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
